### ISSUE TITLE
Clean up the Noir code

### ISSUE THREAD

**Issue by 0xkzam** [0xkzam/zk-auth#4]
I'm getting the following warning in the `yarn deploy --reset` step
------------------------------------------------------------------

compiling circuits...
/Users/kasun/Documents/dev_env/zk-auth/packages/noir/circuits/AssetGating
warning: Unused expression result of type bool
   ┌─ /Users/kasun/Documents/dev_env/zk-auth/packages/noir/circuits/AssetGating/src/main.nr:65:5
   │  
65 │ ╭     std::ecdsa_secp256k1::verify_signature(
66 │ │       issuer_public_key_x,
67 │ │       issuer_public_key_y,
68 │ │       issuer_signed_message,
69 │ │       claim_payload,
70 │ │     );
   │ ╰─────'
   │  

🤓 trying to read: ./circuits/AssetGating/target/AssetGating.json
exporting sol verifiers...
circuits/AssetGating/
warning: Unused expression result of type bool
   ┌─ /Users/kasun/Documents/dev_env/zk-auth/packages/noir/circuits/AssetGating/src/main.nr:65:5
   │  
65 │ ╭     std::ecdsa_secp256k1::verify_signature(
66 │ │       issuer_public_key_x,
67 │ │       issuer_public_key_y,
68 │ │       issuer_signed_message,
69 │ │       claim_payload,
70 │ │     );
   │ ╰─────'
   │  

[AssetGating] Contract successfully created and located at /Users/kasun/Documents/dev_env/zk-auth/packages/noir/circuits/AssetGating/contract/AssetGating/plonk_vk.sol
WARNING: You are using a version of Node.js that is not supported, and it may work incorrectly, or not work at all. See https://hardhat.org/nodejs-versions

Compiling 10 Solidity files
Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
   --> contracts/verifiers/AssetGating.sol:580:21:
    |
580 |     function verify(bytes calldata _proof, bytes32[] calldata _publicInputs) external view returns (bool) {
    |                     ^^^^^^^^^^^^^^^^^^^^^

Warning: Function state mutability can be restricted to pure
  --> contracts/BalloonVendor.sol:25:3:
   |
25 |   function preparePublicInputs(
   |   ^ (Relevant source part starts here and spans across multiple lines).

**Comment by Cryptoineer** [comment]
We can ignore this for now. Once the aztech runtime verification is fixed we use this commented code.
