### ISSUE TITLE
Remove birth year/age  verification messages in the 2nd step

### ISSUE THREAD

**Issue by 0xkzam** [0xkzam/zk-auth#6]
![Screenshot 2024-03-23 at 21 30 46](https://github.com/0xkzam/zk-auth/assets/919641/07464b4e-4209-484f-bf32-40d8031e78a8)
![Screenshot 2024-03-23 at 21 32 35](https://github.com/0xkzam/zk-auth/assets/919641/6582bc40-e29f-493f-9c49-c06fd2c686dd)
![Screenshot 2024-03-23 at 21 41 19](https://github.com/0xkzam/zk-auth/assets/919641/159eb2d1-9f68-4130-b861-9697df18cd91)

**Comment by Cryptoineer** [comment]
fixes applied

**Comment by 0xkzam** [comment]
Still there are signed age/birth related labels and notifications.
