### ISSUE TITLE
Get an error 'Proof generation failed' in the 'Generate Proof' step.

### ISSUE THREAD

**Issue by 0xkzam** [0xkzam/zk-auth#7]
I get an error 'Proof generation failed' in the 'Generate Proof' step. However in the next it says "Successfully verified the proof"????

**Comment by Cryptoineer** [comment]
Proof generation works on a constraint system. In this specific project, The DAO can set up a circuit for a minimum limit of asset holding. For example, to enter the ETH Denver event you need at least 1 Bufficon NFT.  So, User can connect wallet -> Sign his balance with his private key -> Generate proof if the balance is lower then 1 it will fail. In our constraint system while we not fetching the balance from the network for NFT. We need to put balance manually and sign the validate we have is more then 1 thus anything below 2 will fail the constraint and proof will not be generated.


Secondly, On the verification we are still waiting on Aztech to fix it. They have running issue on runtime verification. So, for now it by default verify in our code base. You can check issue here : https://github.com/AztecProtocol/aztec-packages/issues/1845
